# Generated by Django 6.0.2 on 2026-02-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scraped_data', models.JSONField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('business_intelligence', models.JSONField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('json_url', models.URLField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Domain Analysis',
                'verbose_name_plural': 'Domain Analyses',
                'db_table': 'domain_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField()),
                ('training_type', models.CharField(choices=[('objection_handling', 'Objection Handling'), ('product_knowledge', 'Product Knowledge'), ('pitch_strategy', 'Pitch Strategy'), ('competitor_analysis', 'Competitor Analysis'), ('customer_psychology', 'Customer Psychology')], max_length=50)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('estimated_duration_minutes', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_modules', to='domain_intelligence.domainanalysis')),
            ],
            options={
                'verbose_name': 'Sales Training',
                'verbose_name_plural': 'Sales Training Modules',
                'db_table': 'sales_training',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scraped_content_length', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_logs', to='domain_intelligence.domainanalysis')),
            ],
            options={
                'verbose_name': 'Scraping Log',
                'verbose_name_plural': 'Scraping Logs',
                'db_table': 'scraping_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
